### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by Jawlen** [TehCheat/KillCounter#2]
I've been using this for awhile but for some reason now it is behind the preload data and not under it
![counter](https://user-images.githubusercontent.com/49172420/127691511-1a6d6654-1320-489f-b976-9c78fef614b6.jpg)

**Comment by TehCheat** [comment]
This isn't an issue on my private HUD from what I can tell. I'm assuming you're either using a different HUD that needs updated or you need to update to the latest.

**Comment by Jawlen** [comment]
I have redownloaded the 3.15.15 and set this  folder as my source

{
      "Enable": {
        "Value": true
      },
      "Name": {
        "Value": "KillCounter"
      },
      "SourceUrl": {
        "Value": "https://github.com/TehCheat/KillCounter"
      },
      "CommitShaCurrent": {
        "Value": "3a9b14017c5439bf7aebe9a5f9fa24013e1ed185"
      }

It downloaded and compiled as far as I can tell cause it works, its just stuck behind the Preload Data when it used to be under i.

**Comment by TehCheat** [comment]
Which HUD are you using?

**Comment by Jawlen** [comment]
ExileAPI 3.15.15

**Comment by TehCheat** [comment]
I don't support that HUD and the problem you are running into is an issue with that HUD, not this plugin.
